version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres
  app:
    depends_on:
      - postgresdb
    build: ./
    entrypoint: ['sh', '-c', 'npm run migration:run && npm start']
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$POSTGRESDB_HOST
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_PASSWORD
      - DB_NAME=$POSTGRESDB_DATABASE
      - DB_PORT=$POSTGRESDB_DOCKER_PORT
      # # dev-only
      # - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    # # dev-only
    # volumes:
    #   - ./src:/app/src
    #   - /app/node_modules

volumes:
  db:
